name: Main-Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

env:
  CI: true

jobs:
  PR-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Deps
        run: npm ci --no-fund

      - name: Lint and format
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test --if-present -- --coverage
